### ISSUE TITLE
Contributions?

### ISSUE THREAD

**Issue by sbellem** [davebryson/py-abci#1]
Hi! We would like to know whether you are in a position to process contributions? We are considering using py-abci for a project that will need to go through dev, staging, and production phases. For this reason we will most certainly be in a position to make various contributions, ranging from unit tests, continuous integration, packaging, to whatever may need to be improved.

We would rather contribute to an existing community project than starting our own, but at the same time we would need to operate with considerable momentum.

Hence, if you are available for a conversation about possible ways to benefit from contributions we would be most happy to talk with you.

Best regards,
Sylvain

**Comment by davebryson** [comment]
Hi Sylvain,

Yes the intent was to start this and then build out with contributions from the community.   A single, solid, tested Python interface for ABCI would be useful to the community.   Would like to hear more about what contributions you have in mind.

Dave

**Comment by sbellem** [comment]
Hi Dave!

Ah cool! Good to hear! Well I am not so sure yet as we are just getting started, but for now there are five simple things I see we could contribute:

* continuous integration: run the tests on travis or a similar CI service
* code coverage: use a service like codecov or similar to have visibility in the code coverage
* flake8 checks for code style, following pep8
* make the package available on PyPI (that is mainly for convenience so we can simply run something like `pip install abci`
* sphinx docs, and publish on something like readthedocs

Following the above we'll probably try to increase the code coverage even though it is already good (79% from what I tested).

That's all I can think of for now. This is more boilerplate stuff, but I think this is important for a community project.

Our goal will be to help bring `py-abci` to a production ready state in the upcoming months, if possible. So our contributions will be whatever it takes to get there.

We obviously wish to work with you so that is why I asked if you were available to welcome contributions :)

I hope it makes sense to you!

**Comment by davebryson** [comment]
Sounds good.  We can follow the normal GitHub flow - submit a pull request and I'll add.  I already planned to push to pip, just haven't got around to it yet.  But can do that soon.

**Comment by ttmc** [comment]
Hi @davebryson --- I work with @sbellem and would add one other thing at this point:  the license on the code should be made more clear. Currently it's a bit hidden inside the `setup.py` file (`license='Apache2'`). Much better would be to use the GitHub conventions so it's more obvious; see

https://help.github.com/articles/adding-a-license-to-a-repository/

Before we contribute, we'll have to have a "paper trail" (record) that we agree to license our contributions under the Apache2 license (which we will, happily). That can be done by email or whatever you prefer. Sorry if this seems a bit bureaucratic.

**Comment by ttmc** [comment]
I'll create a new issue to make the license more visible / apparent.

**Comment by davebryson** [comment]
Note:  Now available on pip:   `pip install abci`

**Comment by davebryson** [comment]
Closing this as an issue.  It's now available on pip.  Feel free to contribute and raise any other issues you find.  Thanks.

**Comment by davebryson** [comment]
@ttmc @sbellem  Just read the medium post on the integration with Tendermint.  Great work!!  I need to find some time to dig into this a bit more...looks very interesting!

**Comment by ttmc** [comment]
@davebryson I'm sure it didn't come as a surprise --- we're using `py-abci` so that we can use Tendermint :smile:

**Comment by davebryson** [comment]
@ttmc  Looking forward to the updated white paper.   So is the Tendermint AppHash something like the merkle tree root of the DB contents?  I'm really curious how you're calculating agreed upon state from MongoDb

**Comment by ttmc** [comment]
@davebryson We're not releasing an updated white paper with the release of BigchainDB 2.0 Alpha, but we'll probably have a new one in the next few months. As for the Tendermint AppHash, we're using something really dumb for that at the moment but we plan to use a Merkle-tree-based AppHash in the near future (where the leaf nodes are hashes and each of those hashes is computed from one of the valid & committed transactions).
