### ISSUE TITLE
SimpleCounter not working

### ISSUE THREAD

**Issue by pavlovdog** [davebryson/py-abci#12]
I'm trying to get in touch with Tendermint, using your `abci` packet. So, the first thing I've tried is to run the `counter.py` example - and it doesn't work (there are errors from the Tendermint and `counter.py`). I'm working on the:
```bash
$ uname -a
Linux local 4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Here's the list of commands I'm using to run all the stuff:

1. Install `abci` packet into the new virtual environment:
```bash
$ mkdir Tendermint_python && cd Tendermint_python
$ virtualenv --python python3 --no-site-packages venv
$ source venv/bin/activate && pip install abci
```
2. Copy the [counter.py](https://github.com/davebryson/py-abci/blob/master/examples/counter.py) into the `counter.py` file
3. Initialize Tendermint
```bash
$ cd Tendermint_python
$ tendermint --home ".tendermint" init
```
4. Run Tendermint node
```bash
$ tendermint --home ".tendermint" node
```
5. Open another terminal and run `counter.py`
```bash
$ cd Tendermint_python && source venv/bin/activate
$ python counter.py
```

Here's the logs from the Tendermint:
```bash
E[01-17|14:27:39.616] Stopping abci.socketClient for error: proto: bad wiretype for field types.ResponseSetOption.Code: got wiretype 2, want 0 module=abci-client connection=query
```

And `counter.py`'s logs:
```bash
INFO      ABCIServer started on port: 46658
Traceback (most recent call last):
  File "/home/pavlovdog/Desktop/Tendermint_Bitcoin/venv/lib/python3.5/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/pavlovdog/Desktop/Tendermint_Bitcoin/venv/lib/python3.5/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/home/pavlovdog/Desktop/Tendermint_Bitcoin/venv/lib/python3.5/site-packages/abci/server.py", line 132, in __handle_connection
    inbound = socket.recv(1024)
  File "/home/pavlovdog/Desktop/Tendermint_Bitcoin/venv/lib/python3.5/site-packages/gevent/_socket3.py", line 332, in recv
    return _socket.socket.recv(self._sock, *args)
ConnectionResetError: [Errno 104] Connection reset by peer
Wed Jan 17 17:28:53 2018 <Greenlet at 0x7f78626732a8: _handle_and_close_when_done(<bound method ABCIServer.__handle_connection of <a, <bound method StreamServer.do_close of <StreamServ, (<gevent._socket3.socket [closed]  object, fd=-1, )> failed with ConnectionResetError
```

What am I doing wrong? Thanks in advance!

**Comment by davebryson** [comment]
I assume you're using the latest Tendermint?  This is most like due to an issue referenced earlier to changes to the abci proto file.  Hope to get it fixed soon.  As an alternative you can use an older version of Tendermint in the interim

**Comment by pavlovdog** [comment]
@davebryson Thanks for the answer! Can you tell which version should I use and how can I enable this version? I've tried to checkout and reinstall from the sources, but there are some errors (I've created [issue](https://github.com/tendermint/tendermint/issues/1113) on tendermint/tendermint)

**Comment by sbellem** [comment]
If you use Tendermint 0.13, it should work.

**Comment by pavlovdog** [comment]
@sbellem Thank you! However hard I tried `v0.14.0` didn't work and there was absolutly no troubles with `v0.13.0`.
