### ISSUE TITLE
[packaging] When should the proto files be compiled?

### ISSUE THREAD

**Issue by sbellem** [davebryson/py-abci#15]
## Background
Depending on how #9 is resolved it could be that an additional protobuf file (gogo.proto) is needed. Just like the tendermint/abci proto file, it needs to be compiled into a python file. @davebryson pointed out in https://github.com/davebryson/py-abci/issues/9#issuecomment-358135080 that it could be compiled during the setup phase (via `setup.py`). Since the tendermint/abci proto file is pre-compiled and the resulting python file (`types_pb2.py`) is simply included in the package I suggested in PR #14 that the question of when to compile the gogo.proto file be tackled in a joint issue with the case of the tendermint/abci proto file. 

## Useful Links
* [stackoverflow post](https://stackoverflow.com/questions/27843481/python-project-using-protocol-buffers-deployment-issues)
* [How does google/protobuf/python does it?](https://github.com/google/protobuf/blob/master/python/setup.py)
* [bblfsh/client-python approach](https://github.com/bblfsh/client-python/blob/master/setup.py#L86), pointed out by @davebryson in https://github.com/davebryson/py-abci/issues/9#issuecomment-358135080
* [protobuf-setuptools](https://github.com/pupssman/protobuf-setuptools/blob/master/protobuf_setuptools.py)

**Comment by davebryson** [comment]
Thanks for the great info.  gogo.proto sure seems to have complicated things a bit for the Python side.  I need to dig into this a bit more when I have time.

**Comment by davebryson** [comment]
After some experimentation, I think the proto stuff should not be generated on setup as it requires additional dependencies the average user may not have/need.  We can generate updates and commit to repo as needed.   See the abci-v0.10.0 branch.  It includes the latest support for ABCI version 0.10.0.  
Addtionally, tendermint is making a lot of changes to ABCI, etc... so it may be best to keep things simple until it all settles down

**Comment by davebryson** [comment]
Resolved for now.   We build the gogo, abci, and other supporting proto file from TMlibs, as needed and include with source
