### ISSUE TITLE
Make the license more visible / apparent

### ISSUE THREAD

**Issue by ttmc** [davebryson/py-abci#2]
As per my earlier comment on issue https://github.com/davebryson/py-abci/issues/1#issuecomment-339251363 :

The license on the code should be made more visible / apparent. Currently it's a bit hidden inside the `setup.py` file (`license='Apache2'`). Much better would be to use the GitHub conventions so it's more obvious; see

https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by davebryson** [comment]
Done!
