### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by lsankar4033** [davebryson/py-abci#20]
I noticed that this project hasn't had any commits since 1/30/18. 

Just pulled the most recent version of tendermint and tried to run the `counter` example from this project and ran into this errors:
`E[04-06|20:25:55.657] Stopping abci.socketClient for error: EOF    module=abci-client connection=query`

Is this no longer supported? What's the latest version of tendermint/abci that it's supported for?

**Comment by davebryson** [comment]
It appears the recent version of ABCI has changed to use an int64 vs bigendian for the varint.  This is causing more message issues.   Tendermint is rapidly changing which is causing growth issues on clients.

**Comment by davebryson** [comment]
Moving to proper issue

**Comment by lsankar4033** [comment]
ah, makes sense. Ya, probably makes sense to wait for some stability

**Comment by davebryson** [comment]
I'm trying to work through it now.  It's a combination of a few things: 
- Tendermint moving to use gogo/protobuf with namespaces.  So they have to align with python imports
- The addition of another protobuf file located in the 'tmlibs' repository 
- And the change from bigendian int to int64 for the varint that delimits messages
I hope the change were beneficial as it's causing a lot of difficulty for non-go clients.

**Comment by lsankar4033** [comment]
From what I understand they're going through a large refactor of both tendermint and abci and are trying to switch over to using https://github.com/tendermint/go-amino from protobuf. So might be worth waiting for the dust to settle. 

Thanks for the quick responses! Once tendermint seems stable, happy to help with some of this.

**Comment by joemarct** [comment]
Tendermint is now at `version v0.24.0`, is there any effort at the moment to fix the messaging errors?

**Comment by jomarip** [comment]
This seems relevant to an issue I just posted. What was the last functioning version? I am willing to work with that version
