### ISSUE TITLE
tm-bench gives zero Txs/sec against the counter.py example

### ISSUE THREAD

**Issue by joemarct** [davebryson/py-abci#28]
I tried running `tm-bench` tool against the running `counter.py` and `tendermint` node to measure the TPS (transactions per second). I'm always getting zero, while the provided `kvstore` example ABCI app is giving me some numbers.

Setup 1: counter.py app
>  tm-bench -T 10 -r 1000 localhost:26657
```
Stats          Avg       StdDev     Max     Total     
Txs/sec        0         0          0       0         
Blocks/sec     0.900     0.300      1       9 
```

Setup 2: kvstore app that ships with tendermint
> tm-bench -T 10 -r 1000 localhost:26657
```
Stats          Avg       StdDev     Max      Total     
Txs/sec        971       335        1219     9710      
Blocks/sec     0.900     0.300      1        9  
```

Question: Why is Txs/sec always zero for the `counter.py` app?

**Comment by joemarct** [comment]
Additional info that may or may not be related to this:

I ran `abci-cli test` against the running `counter.py` app and it gives an error:
> abci-cli test
```
I[09-15|20:56:29.312] Starting socketClient                        module=abci-client impl=socketClient
Passed test: InitChain
Passed test: SetOption
Failed test: Commit
Commit hash was unexpected. Got 0000000000000000 expected 
Error: CommitTx failed
```

**Comment by davebryson** [comment]
The example counter app expects transactions in serial order: 1,2,3, etc...  - it's part of the checkTx/validate Tx step.  For example: 
`curl http://localhost:46657/broadcast_tx_commit?tx=0x01`

`curl http://localhost:46657/broadcast_tx_commit?tx=0x02`

Are you sending transactions like that?  You can remove this check is you'd like to benchmark it.

**Comment by joemarct** [comment]
@davebryson You're right, the benchmark using `tm-bench` was failing due to serial ordering imposed in checkTx. It works when I comment out that part. Thanks for the pointers.
