### ISSUE TITLE
How to send binary data transactions

### ISSUE THREAD

**Issue by gauthamzz** [davebryson/py-abci#31]
Since the struct pack returns a binary string as an output 
`>>> encode_number(1)
b'\x00\x00\x00\x01'`

and decode also takes this 
` >>> decode_number(b'\x00\x00\x00\x01')
1
`

while the transcations given via curl are given in Hex like 
`curl http://localhost:26657/broadcast_tx_commit?tx=0x01`

How do you convert your binary string to hex easily for curl command ?

**Comment by davebryson** [comment]
See Python docs for this - binascii is a starting place.  Also look at the Tendermint docs for the rpc API

**Comment by gauthamzz** [comment]
I am presently converting the binary to hex like `raw.hex()` after which i copy this value and add after `curl http://localhost:26657/broadcast_tx_commit?tx=0x` and it works. 

Tendermint also supports grpc right? So can you add an example which uses that, if possible? Rather than struct pack.

**Comment by gauthamzz** [comment]
Can you show how to work with 4 nodes local cluster using docker-compose. An example will be very useful.
