### ISSUE TITLE
abcisocket is failing to connect

### ISSUE THREAD

**Issue by jomarip** [davebryson/py-abci#34]
Good Day,
I am trying to run the Counter Example for py-abci. The issue I am facing is that the abcisocket is failing to connect. I have tried different ports, but I am not sure where to start to track down the issue. Initially I was running an old version of tendermint, but even after updating, I still faced the same issue. I would appreciate your guidance and direction

**------------------------------------------------------------------
Some relevant stats about the operating environment**
Running the Windows Subsystem Linux
Python 3.6.8
`iramaj@LAPTOP-241H1D7P:~/.tendermint$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/iramaj/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/iramaj/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build921347695=/tmp/go-build -gno-record-gcc-switches"`

-**--------------------------- Running the counter app-----------------------------**
`iramaj@LAPTOP-241H1D7P:~/Tendermint$ python3 counter.py -p 46658
INFO      ABCIServer started on port: 46658
^Z
[1]+  Stopped                 python3 counter.py -p 46658
iramaj@LAPTOP-241H1D7P:~/Tendermint$ python3 counter.py -p 26658
INFO      ABCIServer started on port: 26658`

-**-----------starting the tendermint node------------------------------------------**
`iramaj@LAPTOP-241H1D7P:~/.tendermint$ tendermint node
E[2019-08-16|17:26:13.189] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying... module=abci-client connection=query err="dial tcp 127.0.0.1:26658: connect: connection refused"
E[2019-08-16|17:26:17.194] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying... module=abci-client connection=query err="dial tcp 127.0.0.1:26658: connect: connection refused"
E[2019-08-16|17:26:21.198] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying... module=abci-client connection=query err="dial tcp 127.0.0.1:26658: connect: connection refused"
E[2019-08-16|17:26:25.203] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying... module=abci-client connection=query err="dial tcp 127.0.0.1:26658: connect: connection refused"
^Z
[1]+  Stopped                 tendermint node
iramaj@LAPTOP-241H1D7P:~/.tendermint$ tendermint version
0.32.2-eec6d33e`

**Comment by davebryson** [comment]
Double check what version of Tendermint you're using.  This version of py-abci works with:

 *ABCI v0.15.0 and Tendermint v0.26.0*

Tendermint has been rapidly upgrading ABCI and that impacts the messages and connections to py-abci.   Unfortunately I've been a little slow keeping up with those changes.

**Comment by davebryson** [comment]
Closing - believe this was a TM version issue

**Comment by jomarip** [comment]
So does it work with the most recent Tendermint version now?
