### ISSUE TITLE
ABCIServer.run() raises an `AttributeError`

### ISSUE THREAD

**Issue by tuxxy** [davebryson/py-abci#41]
```
  File "/home/tux/.cache/pypoetry/virtualenvs/tendies-UGdA5WR3-py3.9/lib/python3.9/site-packages/abci/server.py", line 139, in
run
    gevent.signal(signal.SIGQUIT, evt.set)
AttributeError: module 'gevent' has no attribute 'signal'
```

Any idea what this is? I'm running with Python3.9

**Comment by tuxxy** [comment]
Looks like `gevent.signal` was an alias and it got removed in an updated version for `gevent.signal_handler`.

See: http://www.gevent.org/api/gevent.signal.html
> Changed in version 1.5a4: Previously there was a backwards compatibility alias gevent.signal, introduced in 1.1b4, that partly shadowed this module, confusing humans and static analysis tools alike. That alias has been removed. (See gevent.signal_handler.)

**Comment by tuxxy** [comment]
@davebryson I've opened #42 in response to this issue. Would appreciate any quick feedback to get this released quickly. :)

**Comment by davebryson** [comment]
@tuxxy Thanks for the fix!  I noticed that the latest Gevent is 20.x and this references 1.54...   Should the Pipfile be locked at the 1.54 version?  I appreciate your contributions.

**Comment by tuxxy** [comment]
I don't think it needs to be locked for 1.54. It's just noting that this API changed in 1.54. :)

Sorry for the gap in time! I didn't notice the notification that you replied.
