### ISSUE TITLE
google.protobuf.message.DecodeError: Truncated message.    

### ISSUE THREAD

**Issue by ws160920096** [davebryson/py-abci#44]
Hello, I'm trying to run  counter.py example.
 when run    'tendermint node' ,there are some errors.
![图片](https://user-images.githubusercontent.com/32269053/110410293-9ca57800-80c3-11eb-9de1-f02bc2bb3d66.png)
![图片](https://user-images.githubusercontent.com/32269053/110410386-c3fc4500-80c3-11eb-9fd8-63aa5b322dc6.png)
and  The terminal display is as follows：
![图片](https://user-images.githubusercontent.com/32269053/110410483-e9894e80-80c3-11eb-96ac-3183a4013dfc.png)

**Comment by davebryson** [comment]
Check which version of Tendermint you're using.  This version of py-abci currently support Tendermint 0.32.6.   Using the wrong version of Tendermint will usually cause these types of errors

**Comment by davebryson** [comment]
Closing due to no more information
