### ISSUE TITLE
ABCI server crashes in case of large data messages

### ISSUE THREAD

**Issue by kansi** [davebryson/py-abci#7]
#### Description
I am trying to send data message to tendermint which have large payload size (>1024 bytes). This causes the ABCI server to crash when parsing the message as it [reads 1024 bytes](https://github.com/davebryson/py-abci/blob/master/abci/server.py#L128) and attempts to parse the same.

If this repo is open to contribution then I can generate a PR which would generalize to messages of any size?

**Comment by davebryson** [comment]
@kansi Yes - PRs are welcome

**Comment by davebryson** [comment]
Thanks @kansi  - now merged.    I will need to update PyPi after adding more tests

**Comment by kansi** [comment]
@davebryson below is a little test for `read_message` function

```python
    data4 = BytesIO(b'\x02\x04\x01')
    data4.read(3)
    data4.write(os.urandom(512))
    data4.seek(0)
    req_type, fail = read_message(data4, types.Request)
    assert fail == -1
```
Hope this helps.
