### ISSUE TITLE
Update types.proto & types_pb2.py for latest tendermint (0.15)

### ISSUE THREAD

**Issue by sbellem** [davebryson/py-abci#9]
The go abci `types.proto` has changed and the current py-abci does not work with the Tendermint 0.15.

_Will add more details and steps to reproduce the problem soon._

Also related: https://github.com/bigchaindb/bigchaindb/pull/2005#issuecomment-357947966

In the meantime, this issue seems related: https://github.com/tendermint/abci/issues/179

**Related**: code types (`enum CodeType`) were removed: https://github.com/tendermint/abci/commit/42a8e3240c92e9dddda1e2dd2ca26e155a3d5025#diff-f325a92d451852ea8923aaa3a50731be

**Comment by srmo** [comment]
Subscribing here to see if there's any progress on your side. We have trouble porting jABCI to 0.15+ tendermint because of those new gogoproto types.
https://github.com/jTendermint/jabci/issues/34

**Comment by davebryson** [comment]
So if I'm understanding correctly, this is a fundamental problem with the latest types.proto file in tendermint?

**Comment by sbellem** [comment]
> So if I'm understanding correctly, this is a fundamental problem with the latest types.proto file in tendermint?

Well, since I am not very knowledgeable with protobuf I wish to be careful to make conclusions, but it most certainly complicates things.

I am currently testing the simple approach of removing the annotations, and will report as soon as possible.

**Comment by davebryson** [comment]
At first glance, it looks like you need to add gogo protobuf to your build chain to properly compile it for Python bindings -  but this is a very quick assessment.   Here's an example:

https://github.com/bblfsh/client-python/blob/master/setup.py#L86

**Comment by sbellem** [comment]
Oh, interesting. I have tried using gogoprotobuf, following https://github.com/gogo/protobuf#more-speed-and-more-generated-code but ran into the import problem, reported in https://github.com/cockroachdb/cockroach/issues/393:

> FYI, the python-specific issue here is that protoc's python support assumes that the proto directory structure and python package structure are the same: importing github.com/gogo/protobuf/gogoproto/gogo.proto in a proto file translates to "import github.com.gogo.protobuf.gogoproto.gogo_pb2" in python. Using "github" as a top-level python package is basically a non-starter. Even if this were fixed and the top-level package remapped to "gogoproto", someone would need to own the "gogoproto" python package; there's no clean way for cockroach-python to distribute its own vendored version of gogoproto.

I could try the approach used in the [link](https://github.com/bblfsh/client-python/blob/master/setup.py#L86) you provided.

In the meantime, the approach of removing the annotation yields positive results, but as pointed out by @srmo it does not mean that there cannot be unnoticed negative side effects.

**Comment by srmo** [comment]
I'm currently trying out a more streamlined rebuild with ideas from the links you gave, @sbellem.
Looks promising so far.
What I'm doing is having the gogo.proto from the gogo repo next to the tendermint types proto and do some java options. I'm using the protoc maven plugin and say that it has to include stdTypes (the ones from google) as they are imported from gogo.proto.
This leads to generated files for tendermint.abci and gogoproto which seems to work. Currently still in testing but this looks good. (with the minor caveat that the CodeType type has vanished, nothing a constant class wont fix ;) )

**Comment by sbellem** [comment]
@davebryson just made a PR to show the naive approach of removing the annotations. You can consult the description of the PR for additional details.

I will resume work on this issue tomorrow. I am ok with helping resolving the issue, so please let me know if you prefer to tackle it yourself, or how I can help.

**Comment by davebryson** [comment]
@sbellem  Yes unfortunately I'm currently knee deep in Go programming on Ethereum.  So any help you can provide is greatly appreciated!

**Comment by sbellem** [comment]
@davebryson ah ok, that's fine! Thanks for letting me know! 

So I'll take care of the issue then. Will keep you informed via this issue and PR #11 as progress is made..

**Comment by sbellem** [comment]
> At first glance, it looks like you need to add gogo protobuf to your build chain to properly compile it for Python bindings - but this is a very quick assessment. Here's an example:
> 
> https://github.com/bblfsh/client-python/blob/master/setup.py#L86

@davebryson see PR #14 :smile:

**Comment by davebryson** [comment]
Should be resolved with the latest merges thanks to @sbellem.  Leaving open for now until we test more.

**Comment by davebryson** [comment]
Closing for now.  See abci-0.10.0 branch
